const paragraphs = [
  "Once upon a time, in a quaint village nestled between verdant hills and ancient forests, there lived a young woman named Elara.",
  "The village was renowned for its stunning gardens, each bursting with vibrant flowers and lush greenery.",
  "Elara, with her innate talent for gardening, had the most beautiful garden of all, filled with rare and exotic plants that drew visitors from far and wide",
  "Her love for plants was nurtured by her grandmother, who taught her the art of cultivation and the mystical lore associated with each bloom.",
  "One day, Elara heard of a legendary flower called the Moonlit Blossom, rumored to bloom only under the light of a full moon. This flower was said to have magical properties,",
  "capable of granting a single wish to whoever found it. Captivated by the legend, Elara decided to seek out this elusive bloom. She prepared her tools, packed a small bag, ",
  "Bid farewell to her village, determined to bring back the Moonlit Blossom.Elara's journey was filled with challenges. She trekked through dense forests where the trees",
  "Whispered ancient secrets, crossed rivers whose waters sparkled with hidden gems, and climbed mountains that reached into the clouds. Along the way, she encountered travelers and ",
  "Sages who had heard of the Moonlit Blossom but had never seen it. Despite their warnings about the dangers and the impossibility of the quest, Elara remained steadfast.After weeks of travel,",
  "Elara arrived at a secluded valley bathed in the soft glow of the moon. The air was filled with a mysterious fragrance, and the landscape seemed to shimmer under the moonlight. ",
  "As she wandered through the valley, she noticed a faint, silvery glow coming from a small clearing. There, in the center, stood the Moonlit Blossom, its petals glistening as if ",
  "Kissed by the stars. The sight of the flower took her breath away; it was more beautiful than she had ever imagined.With great care, Elara dug up the Moonlit Blossom, ensuring",
  "That its roots remained intact. She knew the journey back would be challenging, but the thought of the wish it could grant filled her with determination. She returned to her village, ",
  "Where the townspeople welcomed her with awe and celebration. True to the legend, the Moonlit Blossom granted Elara a single wish. She wished for her village to always flourish, ",
  "With abundant gardens and prosperous harvests.The Moonlit Blossom was planted in the village square, where it became a symbol of hope and resilience. Under every full moon, the ",
  "Flower would bloom, casting a soft, ethereal light that brought joy and wonder to all who saw it. Elara's garden grew even more magnificent, attracting botanists and admirers from",
  "Distant lands. Her journey and the discovery of the Moonlit Blossom became a cherished story, passed down through generations.Elara's legacy lived on, reminding everyone of the beauty",
  "Of nature, the power of belief, and the magic that lies in perseverance and hope. The Moonlit Blossom continued to bloom, a symbol of the wondrous and the extraordinary in the everyday world.",
];
